export const GET_ERRORS = "GET_ERRORS";
export const GET_PRODUCTOS = "GET_PRODUCTOS";
export const DELETE_PRODUCTOS = "DELETE_PRODUCTOS";
export const GET_CATEGORIAS = "GET_CATEGORIAS";
export const DELETE_CATEGORIAS = "DELETE_CATEGORIAS";